[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health/chat-integration"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"

[env]
NODE_ENV = "production"
PORT = "3000"
