#!/bin/bash
# Script to get Chatwoot Account ID and Inbox ID from self-hosted instance

echo "🔍 Chatwoot Self-Hosted Configuration Helper"
echo "==========================================="
echo ""
echo "SSH into your Hetzner server and run these commands:"
echo ""
echo "# Option 1: Using Rails Console"
echo "cd /home/chatwoot/chatwoot  # or wherever Chatwoot is installed"
echo "sudo -u chatwoot RAILS_ENV=production bundle exec rails console"
echo ""
echo "# Then in the Rails console, run:"
echo "puts \"Account ID: #{Account.first.id}\""
echo "puts \"Account Name: #{Account.first.name}\""
echo "puts \"Inbox ID: #{Inbox.first.id}\""
echo "puts \"Inbox Name: #{Inbox.first.name}\""
echo "puts \"Website Token: #{Channel::WebWidget.first&.website_token}\""
echo "exit"
echo ""
echo "# Option 2: Using PostgreSQL directly"
echo "sudo -u postgres psql chatwoot_production"
echo ""
echo "# Then run these SQL queries:"
echo "SELECT id, name FROM accounts LIMIT 1;"
echo "SELECT id, name FROM inboxes LIMIT 5;"
echo "SELECT website_token FROM channel_web_widgets LIMIT 1;"
echo "\q"
echo ""
echo "# Option 3: Using Docker (if using Docker installation)"
echo "docker exec -it chatwoot-postgres psql -U postgres chatwoot_production -c \"SELECT id, name FROM accounts;\""
echo "docker exec -it chatwoot-postgres psql -U postgres chatwoot_production -c \"SELECT id, name FROM inboxes;\""
echo "docker exec -it chatwoot-postgres psql -U postgres chatwoot_production -c \"SELECT website_token FROM channel_web_widgets;\""