#!/bin/bash
# Get Chatwoot API Token from Self-Hosted Instance

echo "Run these commands on your Hetzner server:"
echo "=========================================="
echo ""
echo "ssh root@chat.nextnest.sg"
echo ""
echo "# Navigate to Chatwoot directory"
echo "cd /home/chatwoot/chatwoot"
echo ""
echo "# Get API token for your admin user"
echo "sudo -u chatwoot RAILS_ENV=production bundle exec rails runner \""
echo "  user = User.find_by(email: 'assist@nextnest.sg')"
echo "  if user"
echo "    token = user.access_tokens.first_or_create!"
echo "    puts '=================================='"
echo "    puts 'Your API Token:'"
echo "    puts token.token"
echo "    puts '=================================='"
echo "    puts 'Account ID: ' + Account.first.id.to_s"
echo "    puts 'Inbox ID: ' + Inbox.first.id.to_s"
echo "  else"
echo "    puts 'User not found. Available users:'"
echo "    User.all.each { |u| puts u.email }"
echo "  end"
echo "\""